name: snake
version: 0.1

ghc-options:
  - -Werror
  - -Wall

default-extensions:
  - ImportQualifiedPost

library:
  source-dirs: src
  dependencies:
    - base
    - random
    - threepenny-gui

executables:
  # TODO: rename back to 'snake'
  # https://github.com/commercialhaskell/stack/issues/3918
  snake-exe:
    source-dirs: exe
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - snake
      - open-browser
      - threepenny-gui
